title: My Portfolio
description: A showcase of my work and projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Simrannnnnnnnnnnn.github.io" # the URL for your site
theme: minima # example theme
